// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/eth-xrp-scanner/Scanner.tsx": () => import("../components/mockups/eth-xrp-scanner/Scanner.tsx")
};
